/**
 * NOTE: This class is auto generated by the swagger code generator program (1.0.12-1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Exams;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-06-01T16:56:33.976Z")

@Api(value = "getAllStudentsExams", description = "the getAllStudentsExams API")
public interface GetAllStudentsExamsApi {

	@CrossOrigin(origins = "*")
    @ApiOperation(value = "Returns all exams of a certain student of lectures he subscribed in the beginning of a semester", nickname = "getAllExamsOfAStudent", notes = "", response = Exams.class, tags={ "studentsExams", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = Exams.class),
        @ApiResponse(code = 400, message = "Exams couldn't be found"),
        @ApiResponse(code = 404, message = "Exams not found") })
    @RequestMapping(value = "/getAllStudentsExams",
        produces = { "application/json", "application/xml" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<Exams> getAllExamsOfAStudent(@NotNull @ApiParam(value = "The user mkNumber", required = true) @Valid @RequestParam(value = "mkNumber", required = true) String mkNumber);

}
