/**
 * NOTE: This class is auto generated by the swagger code generator program (1.0.12-1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.annotations.*;
import io.swagger.model.Enrollments;

import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-06-01T16:56:33.976Z")

@Api(value = "subscribe", description = "the subscribe API")
public interface SubscribeApi {

	@CrossOrigin(origins = "*")
    @ApiOperation(value = "Student subscribes to an exam", nickname = "subscribe", notes = "This can only be done by the logged in student.", tags={ "subscribe", })
    @ApiResponses(value = { 
        @ApiResponse(code = 400, message = "Invalid exam supplied"),
        @ApiResponse(code = 404, message = "Exam not found") })
    @RequestMapping(value = "/subscribe",
        produces = { "application/json", "application/xml" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Enrollments> subscribe(@NotNull @ApiParam(value = "The user mkNumber", required = true) @Valid @RequestParam(value = "mkNumber", required = true) String mkNumber,@NotNull @ApiParam(value = "The user mkNumber", required = true) @Valid @RequestParam(value = "examId", required = true) String examId);

}
